import "./js/fruitOperation/createMarkup.js";
import "./js/modals/addModal.js";
import "./js/services/getFruitApi.js";
import "./js/services/addFruitApi.js";
import "./js/services/updateFruitApi.js";
import "./js/services/deletFruitApi.js";
import "./js/app.js";
import "./js/fruitOperation/deletFruit.js"
import "./js/services/updateFruitApi.js";
import "./js/modals/closeEditModal.js";
import "./js/modals/openEditModal.js";
import "./js/fruitOperation/getFruits.js";